# Generated by Django 5.0.1 on 2024-06-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0007_alter_lostitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitems',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='lostitems/'),
        ),
    ]
