# Generated by Django 5.0.1 on 2024-06-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0008_alter_lostitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='contact',
            field=models.BigIntegerField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='contact',
            field=models.BigIntegerField(default=None, max_length=50),
        ),
    ]
