# Generated by Django 5.0.1 on 2024-06-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0010_alter_founditems_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
