# Generated by Django 5.1.1 on 2024-10-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRS_attendance', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceregistration',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/'),
        ),
    ]
